version: "3"
services:
  backend:
    container_name: back-nestjs
    image: "node:18"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=30000
    volumes:
      - ./todolist:/home/node/app
    expose:
      - "3001"    
    command: "sh -c 'npm install && npm run start:dev'"
    ports:
      - 3001:3001

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase 

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
