version: "3"
services:
  frontend:
    container_name: front-nextjs
    image: "node:18"
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=30000
    volumes:
      - ./todolist:/home/node/app
    expose:
      - "3000"    
    command: "sh -c 'npm install && npm run dev'"
    ports:
      - 3000:3000
